spring.application.name=zorvyn
server.port=8080
#DataSouce Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/zorvyn
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#Jpa Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#JWT Properties
jwt.secret="em9ydnluLWZpbmFuY2UtZGFzaGJvYXJkLXNlY3JldC1rZXktcGFydGg="
jwt.expiration=86400000

#Spring Doc Properties
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs