spring.application.name=zorvyn
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/zorvyn
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
jwt.secret="R8gdYiKGBI3ms4DYv3ReAvVTTYwO2vYN"
jwt.expiration=86400000